### PR TITLE
Use xkcd-script as the main font

### PR DESCRIPTION
**Pull request by rknoll**
Use the amazing xkcd-script font from [ipython/xkcd-font](https://github.com/ipython/xkcd-font) as the main app font and keep roboto as a fallback. Also adds attribution to the info dialog and the original license.
Partially addresses #19 by using a comic like font, lines and borders are still straight though.
image
image

### CODE REVIEW

**Comment by glennhartmann** [comment]
Code looks good, but I assume you know what you're doing with licensing, because I don't.

I think you also need a package.json change

```
ERROR in ./client/theme/index.js
Module not found: Error: Can't resolve 'xkcdplot/humor-sans' in '/home/glenn/dev/draw/client/theme'
 @ ./client/theme/index.js 4:0-29
 @ ./client/components/App.js
 @ ./client/index.js
```

**Review by glennhartmann — COMMENTED** [review]
Maybe I'm supposed to put this comment here? I've never reviewed a github PR before.

> Code looks good, but I assume you know what you're doing with licensing, because I don't.
>
> I think you also need a package.json change
>
> ERROR in ./client/theme/index.js
> Module not found: Error: Can't resolve 'xkcdplot/humor-sans' in '/home/glenn/dev/draw/client/theme'
>  @ ./client/theme/index.js 4:0-29
>  @ ./client/components/App.js
>  @ ./client/index.js

**Review by glennhartmann — CHANGES_REQUESTED** [review]
Oh, I was also supposed to request changes.

> I think you also need a package.json change

**Comment by rknoll** [comment]
> Code looks good, but I assume you know what you're doing with licensing, because I don't.
> 
> I think you also need a package.json change
> 
> ```
> ERROR in ./client/theme/index.js
> Module not found: Error: Can't resolve 'xkcdplot/humor-sans' in '/home/glenn/dev/draw/client/theme'
>  @ ./client/theme/index.js 4:0-29
>  @ ./client/components/App.js
>  @ ./client/index.js
> ```

Whoops, that import shouldn't be there, fixed. I should have probably made another commit with the fix and only squash them once I merge the PR.. Oh well :-)

**Comment by rknoll** [comment]
Re license: I have no idea what I'm doing either, but
1) This shouldn't get too much attention
2) I did add the License file and attribution to the page itself
3) This will never be used for profit nor will it have ads, I promise ✌️
4) Randall seems to be quite relaxed about [licenses](https://xkcd.com/license.html)

**Review by glennhartmann — APPROVED** [review]
lgtm

**Pull request merged**
